export default class Asset_Availability_PageObjects {
    public static AssetAvailability = {
        Breadcrumb:"//ul[@class='breadcrumb']",
      Otheruser: '//a[text()="Other User"]',
      Username: '#username',
      Password: '#password-field',
      Login: '#login-submit',
      ClickMenu: '//*[@title="Access Based Menu"]',
      grid:"//kendo-grid/div/div/div/table/thead/tr",
      alert_box:"//eiptoastalert",
      company:"(//p[@class='value'])[5]",
      CompanyGrid:'//tbody//tr',
      Asset_Management:"//span[text()=' Asset Availability ']",

      AvailableOwnedSection:'//section//div[@class="d-flex align-items-center position-relative active-card"]//div',
      AssetManagement: '//span[text()="Asset Management"]',
      PlanningAndProcurement: '//span[text()="Planning & Procurement"]',
      AssetAvailability: '//span[text()="Asset Availability"]',
      drpJoblistHR:'//input[@id="drpJoblistHR"]',
      JobListHR_select:'//span[text()="LE150530 - Ghoshpukur Salsalabari Road Project"]',
      input:'//input[@class="k-input"]',
      Input_Selection:"//li[text()='0105 - Bulldozer - 165 HP - 19 T Class']",
      button:'//button[text()="Go"]',
      AvailableOwned: '//p[@class="active-head"]',
      AvailableOwnedjob: '//p[@class="value"]',
      AvailableOwnedCluster: '//div[@id="availableCluster"]',
      Cluster_table:'//span[text()="Cluster"]',
      AvailableOwnedBU: '//p[@class="value"]',
      AvailableOwnedIC: '//div[@id="availableIC"]',
      AvailableOwnedCompany: '//*[@id="availableCompany"]/p[1]',
      SurplusOwned:'//p[@class="non-active-head"]',
      SurplusOwnedjob: '//p[@class="non-active-head"]',
      SurplusOwnedcluster:'//div[@id="surplusCompany"]',
      SurplusOwnedBU: '//div[@id="surplusBU"]',
      SurplusOwnedIC: '//div[@id="surplusIC"]',
      SurplusOwnedCompany: '//div[@id="surplusCompany"]',
      AvailableHired:'//p[text()="Available-Hired"]',
      AvailableHiredjob:'//div[@id="hiringJobId"]',
      AvailableHiredcluster:'//div[@id="hiringCluster"]',
      AvailableHiredBU:'//div[@id="hiringBU"]',
      AvailableHiredIC:'//div[@id="hiringIC"]',
      AvailableHiredCompany:'//div[@id="hiringCompany"]',
      dropdownmenu:'//select[@aria-label="items per page"]',
      ExcelDownload:'//i[@id="ibtExcelImport"]',
      Filtericon:'//i[@id="filterIcon"]',
      Filter:'(//input[contains(@class,"textbox")])[2]',
      Cluster_Value:'//span[text()=" 544 - TI IC - Kolkata Cluster"]',
      JobList: "//div[@role='listbox']",
      AssestCode: "//td[@data-kendo-grid-column-index='0']",
      AssestDescription:"//span[@id='assetDesId']",
      JobDescription:"//span[@id='jobTooltip']",
      Cluster:"//span[@id='clusterID']",
      IC:"//span[@id='icId']",
    }
}