export default class AssestTechnicalDetailsMaster_PageObjects {
    public static LoginPage = {
        Breadcrumb:"//ul[@class='breadcrumb']",
      Otheruser: '//a[text()="Other User"]',
      Username: '#username',
      Password: '#password-field',
      Login: '#login-submit',
      ClickMenu: '//*[@title="Access Based Menu"]',
      alert_box:"//eiptoastalert",
      company:"(//p[@class='value'])[5]",
      CompanyGrid:'//tbody//tr',
      Asset_Management:"//span[text()=' Asset Availability ']",
      AssetManagement: '//span[text()="Asset Management"]',
      PlanningAndProcurement: '//span[text()="Planning & Procurement"]',
      AssetAvailability: '//span[text()="Asset Availability"]',
      Inspection_Technical_Details_Entry:"//span[text()='Inspection & Technical Detail Entry']",
      Assest_Details_master:'//span[text()="Asset Technical Details and Master"]',
      Asset_Technical_Details_Master_IC:"//input[@id='CEGrp']",
      Asset_Technical_Details_Master_job:"//input[@id='jobGrp']",
      Asset_Technical_Details_Master_categorygrp:"//input[@id='categoryGrp']",
      Assest_Technical_Details_ownercode:"//input[@id='ownerGrp']",
      Assest_Technical_Details_Status:'(//input[@id="ownerGrp"])[2]',
      Assest_Technical_Details_Assest:"//input[@class='k-input']",
      Assest_DropDown:'//span[@class="k-select"]',
      Assest_Technical_Details_Search:"//button[@class='btn btn-primary']",
      New_Assest_Create:'//kendo-grid // button',
      New_Assest_Assest_Type:"//input[@id='asset']",
      New_Assest_Type_Click:'//span[text()="5 - Part Addition (Value addition)"]',
      New_Assest_Job_code:"//input[@id='jobGrpAssetNew']",
      New_Assest_Assest_Grp:"//input[@id='assetGrp']",
      New_Assest_Assest_Description:`//mat-label[text()='Asset Decription'] / ancestor :: mat-form-field // input`,
      New_Assest_DC_Number:`//mat-label[text()='DC Number'] / ancestor :: mat-form-field // input`,
      New_assest_Date_Picker:`(//span[@title='Toggle calendar'])[1]`,
      New_assest_Date_Today:' //span[text()=" TODAY "]',
      New_Assest_Received_Date_Picker:'(//span[@title="Toggle calendar"])[2]',
      New_Assest_Po_Number:"//mat-label[text()='PO Number']/ancestor :: span/preceding-sibling :: input",
      New_Assest_Purchase_Date_Picker:'(//span[@title="Toggle calendar"])[3]',
      New_assest_Purchase_Value:'//input[@data-placeholder="Purchase Value"]',
      New_Assest_PurchaseValue_Clear:'//input[@data-placeholder="Purchase Value"]/parent :: div/following-sibling :: div',
      New_Assest_Acquisition_Value:'//input[@data-placeholder="Acquisition Value"]',
      New_Assest_Acquisition_DatePicker:'(//span[@title="Toggle calendar"])[4]',
      New_Assest_Added:'//p[text()="Create Asset"]',
      Assest_Excel_Download:'(//i[@id="ibtExcelImport"])',
      asserts_Excel_Expand:'(//i[@title="Expand"])',
      Parent_Assest_Code:"//input[@id='parantAssert']",
      Cummulative_depriciation:"//input[@data-placeholder='Cumulative depreciation']",
    }
}