export default class BreakDown_PageObjects{
    public static Breakdown = {
        Operations_Maintainance:"//span[text()='Operations & Maintenance']",
        Break_Down_Entry:"//span[text()='Break Down Entry']",
        Break_Down_Job:"//input[@id='job']",
        Break_Down_Assest:"//input[@id='asset']",
        Break_Down_Duration:"//a[@id='icon-rightdateRange_Kendo']",

        CalenderHeader:"(//kendo-calendar-header/span)[1]",
        CalenderMonth:"//td[@title='2024 May']",
        CalenderDate:"(//kendo-virtualization)[2] / descendant :: td/span[text()='15']",

        BreakdownSubmitOk:"//eipmessagebox/descendant :: button",
        Duration_input:"//input[@id='icon-rightdateRange_Kendo']",
        Break_Down_Date_Today:'//span[text()=" TODAY "]',
        Break_Down_Search:"//button[@id='btnTRSearch']",
        Break_Down_Add_Icon:"//i[@title='Add']",
        Break_Down_Toggle:"//span[text()='Break Down ']",
        Break_Down_Type:"//input[@id='eipAutoCompleteDowntimeType']",
        Break_Down_Type_Clear:"//span[@title='clear']",
        Break_Down_From_DatePicker:"(//span[@class='k-icon k-i-calendar'])[1]",
        Break_Down_From_Date:'//kendo-virtualization/table/tbody/tr[6]/td[2]/span',
        Date_Click:"//kendo-calendar-header/span[1]",
        Break_Down_Nature_of_Defect:"//input[@id='eipAutoCompleteNatureOfDefect']",
        Break_Down_Exp_Commonsioning_Date:"(//kendo-datepicker/span/span/span)[2]",
        Break_Down_Time:"(//span[@unselectable='on'])[3]",
        Commissioning_Time:"(//span[@unselectable='on'])[7]",
        Break_Down_Remarks:"//textarea[@id='remarksInput']",
        Submit_btn:"//button[@id='btnSubmit']",
        Detailed_Estimation_toggle:"//mat-button-toggle/descendant :: span[text()='Detailed Estimation ']",
        FailureInvestigation_toggle:"//p[text()='Failure Investigation/Cause(s) of failure']",
        TextArea:"//textarea",
        SubAssembly_toggle:"//p[text()='Sub Assembly']",
        SubAssemblyInput:"//input[@data-placeholder='Sub Assembly']",
        AgencyNameInput:"//input[@placeholder='Agency Name']",
        NatureofRepairInput:"//mat-label[text()='Nature of Repair']/ancestor :: span/ preceding-sibling:: input",
        SparesCostInput:"//mat-label[text()='Spares Cost']/ancestor :: span/ preceding-sibling:: input",
        LabourCostInput:"//mat-label[text()='Labour Cost']/ancestor :: span/ preceding-sibling:: input",
        OilCostInput:"//mat-label[text()='Oil Cost']/ancestor :: span/ preceding-sibling:: input",
        ConsumableCostInput:"//mat-label[text()='Consumable Cost']/ancestor :: span/ preceding-sibling:: input",
        AgencyRepaireCostInput:"//mat-label[text()='Agency Repairs Cost']/ancestor :: span/ preceding-sibling:: input",
        OthersCostInput:"//mat-label[text()='Others Cost']/ancestor :: span/ preceding-sibling:: input",
        SubmitAssemblyClear:"//div[text()=' Clear']",
        SubmitAssemblySave:"(//div[contains(text(),'Save')])[1]",
        MajorSpares:"//p[text()='Major Spares']",
        MaterialsInput:"//input[@placeholder='Materials']",
        PartNoInput:"//mat-label[text()='Part No.']/ancestor :: span/ preceding-sibling:: input",
        PartNameInput:"//mat-label[text()='Part Name']/ancestor :: span/ preceding-sibling:: input",
        QuantityInput:"//mat-label[text()='Quantity']/ancestor :: span/ preceding-sibling:: input",
        AmountInput:"//mat-label[text()='Amount']/ancestor :: span/ preceding-sibling:: input",
        MajorSparesSubmit_btn:"//div[contains(text(),'Submit')]",
        DER_generated:"//eipalertwithtrace/descendant :: p",
        Confirmation_OK:"//button[text()='Ok']",

        Commissioning_toggle:"//mat-button-toggle/descendant :: span[text()='Commissioning ']",
        Commissioning_datepicker:"(//span[@class='k-icon k-i-calendar'])[1]",
        Maintenance_datepicker:"(//span[@class='k-icon k-i-calendar'])[2]",
        Maintenance_month:"(//span[text()='Aug'])[1]",
        Own_button:"//span[text()='Own']",
        Agency_button:"//span[text()='Agency']",
        Both_button:"//span[text()='Both']",
        Vendor_input:"//input[contains(@placeholder,'Vendor')]",
        PandMIncharge_input:"//input[@data-placeholder='P&M Incharge']",
        Workdone_textarea:"(//textarea)[2]",
        Remarks_textarea:"(//textarea)[3]",
        DER_Inputfield : "//thead/descendant :: td[@aria-colindex='6']/ descendant :: input",
        Assetcode_click : "//tbody/descendant :: tr[@data-kendo-grid-item-index='0']/descendant :: td[@aria-colindex='1']/ descendant :: a",


        Rejection_remarks:"//i[@title='Rejection remarks']",
        Rejection_data:"//kendo-popup/ descendant :: p",
    }

    public static Approval = {
        DocumentNO_inputfield:"//thead/descendant :: td[@aria-colindex='2']/ descendant :: input",
        DocumentNo_click :"//tbody/descendant :: tr[@aria-rowindex='3']/descendant :: td[@aria-colindex='2']/ descendant :: a",
        Approve_icon:"//i[@title='Approve']",
        Reject_icon :"//i[@title='Reject']",
        Confirmation_remarks:"//eipconfirmationlistmessagebox/ descendant :: textarea",
        Confirmation_yes :"(//eipconfirmationlistmessagebox/ descendant :: button)[1]",
    }


}