export default class Movements_Asset_PageObjects {
    public static DA = {

      Asset_btn:"//p[text()='Asset']",
      DespatchAdvice:'//span[text()=" Despatch Advice "]',
      MovementAssetCode:"//input[@id='asset']",
      MovementsinputAssetcode:"//span[@class='highlightText']",
      AssetCode_Input_Given:'//input[@id="asset"]',
      MovementsGoButton:"//div[@class='go-button']",
      sourcedestination:"//p[@class='mxy-0 ff-3 fs-15']",
      SourceJob:"//input[@id='ActxtboxGINJob']",
      Sourcewarehouse:"//input[@id='ActxtboxGINWarehouse']",
      SourceCountry:"//input[@id='actxtSMDCountry']",
      SourceState:"//input[@id='actxtSMDState']",
      GSTNumber:"//input[@id='fromGSTTaxRegNoId']",
      ContactDetails:"//input[@aria-label='NO DATA FOUND']",
      sourceMobilenumber:"//input[@id='fromMobileNumberId']",
      sourcemailaddress:"//input[@id='fromEmailAdressId']",
      destination_Job_Input: "//input[@id='frToJob']",
      Destinationjobcode:'//span[contains(text(),"LE150002")]',
      Destinationwareshouse:"//input[@id='frToWarehouse']",
      Destinationcountry:"//input[@id='actxtSMDCountry2']",
      DestinationState:"//input[@id='actxtSMDState2']",
      DestinationName:"(//input[@placeholder='Name']) [2]",
      DestinationMobileNumber:"//input[@id='toMobileNumberId']",
      DestinationEmail:"//input[@id='toEmailAdressId']",
      Accessories:"//p[text()='Accessories']",
      Accessories_Description:"//input[@size='1']",
      Accessories_UOM:"//input[@id='ddlUomId']",
      Accessories_Quantity:"//input[@id='qtyId']",
      Accessories_Add:"//div[@class='g-7 d-flex align-items-center justify-content-center']",
      Accessories_edit:"//i[@class='fa fa-edit']",
      Accessories_update:"//div[@class='g-7 d-flex align-items-center justify-content-center']",
      Accessories_delete:"//table/tbody/tr[1]/td[4]/div/div[2]/i",
      Despatch:"#dispatchPurposeId",
      Remarks:"#remarksId",
      Transportation:"//p[text()='Transportation']",
      TransportationType:"//input[@id='intConfigId']",
      ApproxWeight:"//input[@id='approxWeightId']",
      ApproxDistance:"//input[@id='approxDistanceId']",
      Dimension:"//input[@id='ddlUomId']",
      Length:"//input[@id='lengthId']",
      Breadth:"//input[@id='breathId']",
      Height:"//input[@id='heightId']",
      ReachDestination:"//input[@id='destinationDaysId']",

      Schedule_From_Input:"(//input[@role='spinbutton'])[2]",
      Schedule_From_DatePicker:"(//span[@class='k-icon k-i-calendar'])[1]",
      ScheduleFrom_Today:'//span[text()=" TODAY "]',

      Dispatch_Schedule_To_Input:"(//input[@role='spinbutton'])[3]",
      Dispatch_Schedule_To_DatePicker:"(//span[@class='k-icon k-i-calendar'])[2]",
      Dispatch_ScheduleTo_Today:'//span[text()=" TODAY "]',
     

      Shopping_Cart:"//i[@class='fa-shopping-cart fs-20 pointer']",
      Choosevechicle:"//div/div[2]/div/div[1]/mat-form-field/div/div[1]/div/input",
      SelectVechicle:"//div/div[1]/div/div[2]/div/div[2]/div/button[2]/i",
      Transport_option1:"//span[text()='1 - Single Load (Internal)']",
      Transport_option2:"//span[text()='2 - Multiple Load (Internal)']",
      Transport_option3:"//span[text()='3 - External']",
      Transport_option4:"//span[text()='4 - Not Required']",
      Vehicles_option1:'//div[text()=" VEH006 - Full Truck Load "]',
      Vehicles_option2:' //div[text()=" VEH007 - LPT (Light Truck) Tata 1109 "]',
      Vehicles_option3:' //div[text()=" VEH019 - 20 Feet Single Axle Container "]',
      Vehicles_button:"(//button[1]/i)[1]",
      Selected_VechiclePost:"//eipgeneralcart/descendant::button[text()='Post'][2]",
      Vechiclescount1:"//input[@id='vehicleCountId']",
      Vechiclescount2:"//table/tbody/tr[2]/td[4]/input",
      Vechiclescount3:"//div[1]/table/tbody/tr[3]/td[4]/input",
      Vechiclescount4:"//table/tbody/tr[4]/td[4]/input",
      Vechicletype_delete:"//i[@class='fa fa-trash']",
      Vechiclesubmit:"//p[text()='Submit']",
      Successbutton:"//button[@class='btn btn-primary btn-sm cursor-pointer']",
      Dispatchadvice_Component:"//p[text()='Component']",
      Checkbox:"//span[@class='mat-checkbox-inner-container mat-checkbox-inner-container-no-side-margin']",
      Deliverychallan:"//mat-button-toggle[2]/button/span",
      Reset:"//p[text()='Reset']",
      // save_draft:"//p[text()='Save & Draft']",
      submit:"//p[text()='Submit']",
      PDAgenerated:"//eipmessagebox/ descendant :: p[3]",
      
    }

    public static DC ={
      DeliveryChallan:"//mat-button-toggle[@value='delivery']",
      Deliverychallan_Go:"//i[@title='Go']",
      DANumber_input:"//thead/ descendant::tr[2]/td[2]/ descendant :: input",
      DCEssentials:"//p[text()='DC Essentials']",
      NumberofDCS:"//input[@id='NoOfDc']",
      FMV_value:"//input[@id='FMVValue']",
      Save_Dc:"//p[text()='Save DC']",
      DeliveryChallan_Success:"//button[@class='btn btn-primary btn-sm cursor-pointer']",
      LRandLoad:"//div[2]/div[1]/div[3]/p",
      code:"//kendo-grid/div/kendo-grid-list/div/div[1]/table/tbody/tr/td[6]",
      create_Dc:'//i[@title="Create DC"]',
      Loaddetails:"(//*[text()='Load Details'])[2]",
      LRNumber:"(//div[1]/input[@type='text'])[2]",
      LRDate:"//span[@class='k-icon k-i-calendar']",
      VechicleNumber:"//app-shipment-dialog/div[2]/div[1]/div/div/div[3]/input",
      Transporter:"//app-shipment-dialog/div[2]/div[1]/div/div/div[4]/input",
      FMV_input:"//p[text()=' FMV ']/ following-sibling :: input",
      FrieghttoPayPaid:"(//div[1]/input[@type='text'])[4]",
      Currency:"(//div[1]/input[@type='text'])[3]",
      FreightAmount:"//p[text()=' Freight Amount ']/ following-sibling :: input",

      PDCGenerated:"//eipmessagebox/ descendant :: p[3]",
      SuccessOK:"//eipmessagebox/ descendant :: button",
      LoadDetails:"//p[text()='Load Details']/ following-sibling :: button",
      Accessories:"//p[text()='Accessories']/ following-sibling :: button",
      Description:"//tbody/ descendant::tr[1]/td[1]/ descendant :: input",
      Quantity:"//tbody/ descendant::tr[1]/td[3]/ descendant :: input",
      LoadFMV:"//tbody/ descendant::tr[1]/td[4]/ descendant :: input",
      SaveLoadDetails:"//tbody/ descendant::tr[1]/td[6]/ descendant :: button[3]",
      SaveAccesories:"//tbody/ descendant::tr[1]/td[4]/ descendant :: button[3]",
      EditAccessories:"//tbody/ descendant::tr[1]/td[4]/ descendant :: button[1]",
      SubmitLoad:"//p[text()='Submit (Load Details)']",

  }

  public static RN = {
    DCNumber_input:"//thead/ descendant::tr[2]/td[2]/ descendant :: input",
    Hover:"//table[@class='k-grid-table']/tbody/tr[1]/td[7]/span",
    Create : "(//i[@title='Create RN'])[1]",
    Status:"(//tbody)[2]/descendant::td[@aria-colindex='8']",
    Action:"(//tbody)[2] / tr[1] / td[@aria-colindex='9'] / descendant :: i",
    YesToggle:"//button[text()='Yes']",
    Calendar : "//span[@title='Toggle calendar']",
    Today:"//span[@class='k-today']",
    Remarks : "//textarea[@id='rnRemarks']",
    IssueRN : "//p[text()='Issue RN']",
  }

  public static Commissioning = {
    DCNumber_input:"//thead/ descendant::tr[2]/td[1]/ descendant :: input",
    Hover:"//table[@class='k-grid-table']/tbody/tr[1]/td[7]/span",
    Create_Commissioning:"(//i[@title='Create Commissioning'])[1]",
    Calendar : "//span[@title='Toggle calendar']",
  }
}